kind: pipeline
name: default

steps:
  - name: app-test
    image: meishixiu/policr:build
    pull: true
    commands:
      - shards --production
      - mkdir data
      - POLICR_ENV=test crystal sam.cr -- db:setup
      - POLICR_ENV=test crystal spec

  - name: assets-build
    image: node:stretch
    commands:
      - npm install --prefix ./assets
      - npm run deploy --prefix ./assets

  - name: app-build
    image: meishixiu/policr:build
    pull: true
    commands:
      - shards build policr --release --progress --production --warnings=all
      - crystal sam.cr -- digests:make
      - crystal sam.cr -- digests:clean_undigested

  - name: app-image-push
    image: plugins/docker
    settings:
      repo: meishixiu/policr
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push

  - name: sam-build
    image: meishixiu/policr:build
    pull: true
    commands:
      - shards build sam --release --progress --production --warnings=all
    when:
      branch:
        - sam/update
      event:
        - push

  - name: sam-image-push
    image: plugins/docker
    settings:
      repo: meishixiu/policr
      username:
       from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: sam.Dockerfile
      tags: sam
    when:
      branch:
        - sam/update
      event:
        - push
