version: "3"

services:
  server:
    image: meishixiu/policr
    stdin_open: true
    ports:
      - 8090:8080
    environment:
      POLICR_BOT_TOKEN: "${POLICR_BOT_TOKEN}"
      POLICR_BOT_USERNAME: "${POLICR_BOT_USERNAME}"
      POLICR_BOT_OWNER_ID: "${POLICR_BOT_OWNER_ID}"
      POLICR_BOT_COMMUNITY_GROUP_ID: "${POLICR_BOT_COMMUNITY_GROUP_ID}"
      POLICR_BOT_SNAPSHOT_CHANNEL: "${POLICR_BOT_SNAPSHOT_CHANNEL}"
      POLICR_BOT_VOTING_CHANNEL: "${POLICR_BOT_VOTING_CHANNEL}"
    restart: always
